Models/BookViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace BookFavorites.Models
{
    public class BookViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public int Year { get; set; }
        public int CategoryId { get; set; }

        public string CategoryName { get; set; }
        public List<SelectListItem> Categories { get; set; }
        public IFormFile Image {  get; set; }
        public string ImageURL { get; set; }

    }
}

Models/CategoryViewModel.cs
namespace BookFavorites.Models
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace BookFavorites.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BookController.cs
using BookFavorites.Data;
using BookFavorites.Data.Models;
using BookFavorites.Models;
using BookFavorites.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Reflection;

namespace BookFavorites.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IShortStrings service;
        private readonly IWebHostEnvironment webHostEnvironment;

        public BookController(ApplicationDbContext db, IShortStrings service, IWebHostEnvironment webHostEnvironment)
        {
            this.db = db;
            this.service = service;
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add()
        {
            List<SelectListItem> categories = db.Categories
                .Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                })
                .ToList();
            BookViewModel model = new BookViewModel
            {
                Categories = categories
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(BookViewModel model)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(model);
            //}
            var extansion = Path.GetExtension(model.Image.FileName);
            var dbImage = new Image
            {
                Extension = extansion,
            };
            var physicalPath = $"{webHostEnvironment.WebRootPath}/img/{dbImage.Id}.{dbImage.Extension}";
            using (FileStream fs =new FileStream(physicalPath, FileMode .Create))
            {
                model.Image.CopyTo(fs);
            }

            Book book = new Book
            {
                Title = model.Title,
                Author = model.Author,
                Description = model.Description,
                Year = model.Year,
                CategoryId = model.CategoryId
            };
            book.Images.Add(dbImage);
            db.Books.Add(book);
            db.SaveChanges();
            return Redirect("/Home/Index");
        }
        public IActionResult    Details(int id)
        {
            var model = db.Books.Where(x => x.Id == id).Select(z => new BookViewModel
            {

                Title = z.Title,
                Author = z.Author,
                Description = service.GetShort(z.Description, 40),
                Year = z.Year,
                CategoryName = z.Category.Name,
                ImageURL = "/img/" + z.Images.FirstOrDefault().Id + z.Images.FirstOrDefault().Extension
            }).FirstOrDefault();
            return View(model);
        }
            
        
        public IActionResult All()
        {
            List<BookViewModel> model = db.Books.Select(x => new BookViewModel()
            {
                Title = x.Title,
                Author = x.Author,
                Description = x.Description,
                Year = x.Year,
                CategoryName = x.Category.Name,
            }).ToList();
            return View(model);
         }
        
    
    }
}

Controllers/CategoryController.cs
using BookFavorites.Data;
using BookFavorites.Data.Models;
using BookFavorites.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookFavorites.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext db;

        public CategoryController(ApplicationDbContext db)
        {
            {
                this.db = db; 
            }
        }


        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add()   //GET
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(CategoryViewModel model)
        {
            Category category = new Category
            {
                Name = model.Name,
            };
            db.Categories.Add(category);
            db.SaveChanges();
            return Redirect("/Home/Index");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using BookFavorites.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookFavorites.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Book/Add.cshtml
@model BookViewModel

<h1>Add Book</h1>
</hr>
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"> Title:</label>
        <input type="text" asp-for="Title" class="form-control"/>
        <span asp-validation-for="Title"></span>
        </div>
         <div class="form-group">
        <label asp-for="Description"> Description:</label>
        <input type="text" asp-for="Description" class="form-control"/>
        </div>
        <div class="form-group">
        <label asp-for="Author"> Author:</label>
        <input type="text" asp-for="Author" class="form-control" />
        </div>
         <div class="form-group">
        <label asp-for="Year"> Year:</label>
        <input type="text" asp-for="Year" class="form-control"/>
        </div>
        <div class="form-group">
        <select asp-for="CategoryId" asp-items=@Model.Categories">
        <option> Select category</option>
        <</select>
        </div>
        <div>
            <label asp-for="Image">Image:</label>
            <input type="file" asp-for="Image" class="form-control" />
        </div>
        <div class="form-group">
        </div>
        <div class="form-control">
            <input type="submit" value="Add Book" class="btn btn-primary"/>
        </div>
      

 </form>

Views/Book/All.cshtml
@model IEnumerable<BookViewModel>
<h1> All Book </h1>
<hr/>

<table class=" table table-striped"> 
    <tr>
        <td>Title </td>
        <td>Author</td>
        <td>Description</td>
        <td>Year</td>
        <td>Category</td>
    </tr>
    @foreach (var item in @Model)
    {
        <tr>
            <td>@item.Title</td>
            <td>@item.Author</td>
            <td>@item.Description</td>
            <td>@item.Year</td>
            <td>@item.CategoryName</td>
        </tr>
    }
</table>

Views/Book/Details.cshtml
@model BookViewModel

<h1> Book Info</h1>
<hr />
<p>Title @Model.Title</p>
<p>Author: @Model.Author</p>
<p>Description: @Model.Description</p>
<p>Year: @Model.Year</p>
<p>Category: @Model.CategoryName</p>
<div>
    <img src="@Model.ImageURL" width="35%" /> 
</div>

Views/Category/Add.cshtml
@model CategoryViewModel
<h1>Add Category</h1>
<hr/>
<form method="post">
    <div class="form-control"
    <label asp-for="Name">Category Name</label>
    <input type="text" asp-for="Name"/>
    </div>
    <input type="submit" value="submit"/>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookFavorites</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookFavorites.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookFavorites</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Add">Add Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="All">All Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Add">Add Category</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BookFavorites - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>